open import Util
open import Grammar
open import TermJudgments
open import Subtyping
open import Substitution
open import SubstitutionLemmas
open import TypeJudgments


foo-word : WordValue
foo-word = globval 0 5 ⟦⟦ α (α⁼ 4) ∷ α (α⁼ 4) ∷ α (α⁼ 4) ∷ α (α⁼ 4) ∷ ρ (ρ⁼ 4) ∷ [] ⟧⟧

foo : InstructionSequence
foo = jmp (word foo-word)

foo-Γ : RegisterAssignment
foo-Γ = registerₐ (ρ⁼ 4) (α⁼ 0 ∷ α⁼ 1 ∷ α⁼ 2 ∷ α⁼ 3 ∷ [])

foo-Δ : TypeAssignment
foo-Δ = α ∷ α ∷ α ∷ α ∷ ρ ∷ []

foo-τ : Type
foo-τ = ∀[ foo-Δ  ] foo-Γ

foo-word-valid : [ foo-τ ] , [] , foo-Δ ⊢ foo-word of ∀[ [] ] foo-Γ wval
foo-word-valid = of-inst (of-inst (of-inst (of-inst (of-inst (of-globval here (∀-≤ (valid-α ∷ valid-α ∷ valid-α ∷ valid-α ∷ valid-ρ ∷ []) (Γ-≤ (σ-≤ (valid-ρ⁼ (there (there (there (there here))))))
                                                                                                                                             (α⁼-≤ (valid-α⁼ here) ∷
                                                                                                                                              α⁼-≤ (valid-α⁼ (there here)) ∷
                                                                                                                                              α⁼-≤ (valid-α⁼ (there (there here))) ∷
                                                                                                                                              α⁼-≤ (valid-α⁼ (there (there (there here)))) ∷ []))) refl) (valid-zero
                                                                                                                                                                                                            (valid-inst
                                                                                                                                                                                                             (valid-α (valid-α⁼ (there (there (there (there here)))))))) run-inst (subst-registerₐ (subst-ρ-¬inst (subst-inst-> (s≤s z≤n)))
                                                                                                                                                                                                                                                                                     (subst-α-inst (subst-α-¬inst (subst-weaken-≥ z≤n)) ∷
                                                                                                                                                                                                                                                                                      subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                      subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                      subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷ []))) (valid-zero
                                                                                                                                                                                                                                                                                                                                        (valid-inst
                                                                                                                                                                                                                                                                                                                                         (valid-α (valid-α⁼ (there (there (there (there here)))))))) run-inst (subst-registerₐ (subst-ρ-¬inst (subst-inst-> (s≤s z≤n)))
                                                                                                                                                                                                                                                                                                                                                                                                                 (subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                  subst-α-inst (subst-α-¬inst (subst-weaken-≥ z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                  subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                  subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷ []))) (valid-zero
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (valid-inst
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (valid-α (valid-α⁼ (there (there (there (there here)))))))) run-inst (subst-registerₐ (subst-ρ-¬inst (subst-inst-> (s≤s z≤n)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             (subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              subst-α-inst (subst-α-¬inst (subst-weaken-≥ z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷ []))) (valid-zero
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (valid-inst
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 (valid-α (valid-α⁼ (there (there (there (there here)))))))) run-inst (subst-registerₐ (subst-ρ-¬inst (subst-inst-> (s≤s z≤n)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         (subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subst-α-inst (subst-α-¬inst (subst-weaken-≥ z≤n)) ∷ []))) (valid-zero
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       (valid-inst
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        (valid-ρ (valid-ρ⁼ (there (there (there (there here)))))))) run-inst (subst-registerₐ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (subst-ρ-inst (subst-ρ-¬inst (subst-weaken-≥ z≤n)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 subst-α-¬inst (subst-inst-> (s≤s z≤n)) ∷ []))

foo-is : [ foo-τ ] , foo-Δ , foo-Γ ⊢ foo instructionsequence
foo-is = of-jmp (Γ-≤ (σ-≤ (valid-ρ⁼ (there (there (there (there here)))))) (α⁼-≤ (valid-α⁼ here) ∷
                                                                              α⁼-≤ (valid-α⁼ (there here)) ∷
                                                                              α⁼-≤ (valid-α⁼ (there (there here))) ∷
                                                                              α⁼-≤ (valid-α⁼ (there (there (there here)))) ∷ [])) (of-word foo-word-valid)
